# Raspberry Pi CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install Hugo
          command: sudo apt-get install hugo
      - run:
          name: generate Site
          command: |
            pwd
            hugo version
            ls -al
            cat /etc/*-release
            hugo -v
      - run:
          name: display generated Site
          command: ls -al -R

      - run:
          name: make folders
          command: mkdir test-reports

      - store_artifacts:
          path: test-reports/

      - store_test_results:
          path: test-reports/
  deploy:
    docker:
      - image: circleci/python:3.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fc:24:63:d6:76:a1:4f:d5:c3:ef:f0:74:65:0b:e4:64"
      - run:
          name: install SSH clients
          command: sudo apt-get install openssh-client
      - run:
          name: Display Hugo Site
          command: ls -al

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


