# Workflow to publish new Hugo generated blog-site to Hostinger
name: Harry's Blog
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'Hostinger'
    permissions:
      contents: write

    steps:
      - name: Build blog site
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.136.2'
          # extended: true

      - name: set base URL
        run: |
          sed -i 's/baseurl = \"\"/baseurl = \"https:\/\/dogs.harrycollins.tech\/\"/g' config.toml

      - name: Build
        run: hugo --minify

      - name: Deploy
        env:
          PWD: ${{ secrets.SSH_PWD }}
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.SSH_USER }}
          HOST: ${{ secrets.SSH_ADDRESS }}
        run: |
          sshpass -p "$PWD" scp -o StrictHostKeyChecking=no -P $PORT -r ./public $USER@$HOST:~/domains/dogs.harrycollins.tech/public_html
